#!/bin/bash
# Displays a message when shut down

# Stores all the shutdown messages
array[0]="It's been fun"
array[1]="Until next time"
array[2]="Go get 'em tiger"
array[3]="Make it so"
array[4]="See you on the other side"
array[5]="Exhibit no restraint"
array[6]="Rip and tear"
array[7]="Have just the greatest day"
array[8]="Avenge me"
array[9]="Stay safe"
array[10]="Situation normal"
array[11]="PROTOCOL <3"
array[12]="Fly, you fool"
array[13]="Never surrender"
array[14]="See you Space Cowboy"
array[15]="End of the line"
array[16]="A leaf on the wind"
array[17]="You are who you choose to be"
array[18]="Finish the fight"
array[19]="Change da world, my final message. Goodbye"
array[20]="Protocol 3: Protect the pilot"
array[21]="I'm ready! How 'bout you?"
array[22]="Tell 'em to make it count"
array[23]="Negative. I have the gun. Good luck sir"
array[24]="Any way the wind blows..."
array[25]="You'll find me chasing the sun"
array[26]="Hasa Diga Eebowai!"
array[27]="It'll all be okay"
array[28]="Kiss your fist and touch the sky"
array[29]="We can be heroes, just for one day"
array[30]="If I make it through tonight everybody's gonna hear me out"
array[31]="Delta Echo Alpha Delta, walking on the moon forever"
array[32]="You and I are gonna live forever"
array[33]="Slide away"
array[34]="'Cause rainbows won't light up the sky, unless you let it rain"
array[35]="I wanna be the hunter not the hunted, I wanna be the killer not the prey"
array[36]="The dance of life, the hunter and the agile prey"
array[37]="I'll be your sleeper hit, let me take this thing into overdrive"
array[38]="Oh no, not me, we never lost control"
array[39]="Don't wait or play to indecision!"
array[40]="You might as well be running when your feet should hit the sand"
array[41]="Hit 'em right between the eyes"
array[42]="We're on our way here we go, we're gonna take over!"
array[43]="I just wanna cause a little entropy"
array[44]="I'll give them shelter, like you've done for me"
array[45]="One thing I can guarantee, the best things in life, they sure ain't free"
array[46]="How do we sleep while our beds are burning?"
array[47]="Ok, three, two, one, let's jam!"
array[48]="So we all ride for nothing, cause this train never stops"
array[49]="And we'll all float on okay"
array[50]="So please children stop your crying and just sing along with me"
array[51]="Well, hello, goodbye, I'll see you in hell!"
array[52]="Make the sweat drip out of every pore"
array[53]="Here I am, stuck in the middle with you"

# Picks a random quote to send
size=${#array[@]}
index=$((RANDOM%size))

# Displays the appropriate opening message
clear
if [ "$1" = -r ]; then
	echo -e "\nRESTART ENGAGED"
elif [ "$1" = -t ]; then
	echo -e "\nA message to you:"
else
	echo -e "\nSHUTDOWN ENGAGED"
fi

# Displays a message from the array, on a delay
sleep 1
echo -e "\n${array[$index]}"
sleep 3

# If the restart flag is given, restarts
# If the test flag is given, only clears
# Otherwise shuts down
if [ "$1" = -r ]; then
	shutdown now -r
elif [ "$1" = -t ]; then
	clear
else
	shutdown now
fi
